# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tODc_iWTuiNo-7SfHkYdZmP23XYNaxDW
"""

"""
Customer Segmentation ML Application
A machine learning web app for segmenting customers into distinct groups
"""

import pickle
import streamlit as st
import pandas as pd
import numpy as np
import os
import gzip

# Page configuration
st.set_page_config(
    page_title='Customer Segmentation ML',
    page_icon='🎯',
    layout='wide',
    initial_sidebar_state='expanded'
)

# Custom CSS
st.markdown("""
    <style>
    .main-header {
        font-size: 2.5rem;
        color: #FF4B4B;
        text-align: center;
        margin-bottom: 0.5rem;
        font-weight: 700;
    }
    .sub-header {
        text-align: center;
        color: #666;
        margin-bottom: 2rem;
        font-size: 1.1rem;
    }
    .stButton>button {
        width: 100%;
        background-color: #FF4B4B;
        color: white;
        font-weight: 600;
        padding: 0.75rem;
        border-radius: 0.5rem;
    }
    </style>
""", unsafe_allow_html=True)

# Load the model with multiple fallback options
@st.cache_resource
def load_model():
    """Load the trained ML model from pickle file"""

    # Try different file names and compression formats
    model_files = [
        'classifier.pkl',
        'classifier.pkl.gz',
        'model.pkl',
        'final_pipeline.pkl'
    ]

    for model_file in model_files:
        if os.path.exists(model_file):
            try:
                # Handle gzip compressed files
                if model_file.endswith('.gz'):
                    with gzip.open(model_file, 'rb') as f:
                        model = pickle.load(f)
                        st.success(f"✅ Model loaded from {model_file}")
                        return model
                # Handle regular pickle files
                else:
                    with open(model_file, 'rb') as f:
                        model = pickle.load(f)
                        st.success(f"✅ Model loaded from {model_file}")
                        return model
            except Exception as e:
                st.warning(f"⚠️ Failed to load {model_file}: {str(e)}")
                continue

    # If no model file found
    st.error("❌ Model file not found! Please upload classifier.pkl to your repository.")
    st.info("📋 Expected file names: classifier.pkl, classifier.pkl.gz, model.pkl, or final_pipeline.pkl")
    return None

# Load model
classifier = load_model()

# Header
st.markdown('<h1 class="main-header">🎯 Customer Segmentation ML</h1>', unsafe_allow_html=True)
st.markdown('<p class="sub-header">AI-powered customer segmentation for targeted marketing strategies</p>', unsafe_allow_html=True)

# Info section
with st.expander("ℹ️ About This Application", expanded=False):
    col1, col2 = st.columns(2)

    with col1:
        st.markdown("""
        ### 📊 What It Does
        This ML application segments customers into **4 distinct clusters** based on:
        - **Demographics**: Age, income, education, family
        - **Spending**: Purchase amounts across categories
        - **Behavior**: Shopping channels & campaign responses

        ### 🎯 Use Cases
        - Personalized marketing campaigns
        - Product recommendations
        - Customer retention strategies
        - Revenue optimization
        """)

    with col2:
        st.markdown("""
        ### 🏆 Model Performance
        - **Voting Ensemble**: 98.2% accuracy
        - Logistic Regression: 98.9%
        - Random Forest: 95.5%
        - SVM: 97.3%

        ### 👥 Customer Segments
        - 🟢 **Cluster 0**: Moderate spenders
        - 🔵 **Cluster 1**: Budget conscious
        - 🟡 **Cluster 2**: High value
        - 🔴 **Cluster 3**: Premium elite
        """)

def segment_customers(input_data):
    """Predict customer segment with proper error handling"""

    if classifier is None:
        return None, {
            "name": "Model Error",
            "icon": "❌",
            "description": "Model not loaded. Please check if classifier.pkl exists in the repository.",
            "strategy": "Upload the model file to fix this issue."
        }

    try:
        # Create DataFrame from input
        df_input = pd.DataFrame([input_data])

        # Make prediction
        prediction = classifier.predict(df_input)
        cluster_num = int(prediction[0])

        # Cluster information
        cluster_details = {
            0: {
                "name": "Moderate Spenders",
                "icon": "🟢",
                "description": "Average income customers with balanced spending patterns and moderate family size. Regular shoppers with steady engagement.",
                "strategy": "Target with mid-range products, family-oriented campaigns, and seasonal promotions.",
                "characteristics": ["Middle income", "Balanced spending", "Family-focused", "Regular purchases"]
            },
            1: {
                "name": "Budget Conscious",
                "icon": "🔵",
                "description": "Value-focused customers with lower income, seeking essential purchases and good deals. Price-sensitive segment.",
                "strategy": "Focus on value deals, discounts, loyalty programs, and budget-friendly product lines.",
                "characteristics": ["Lower income", "Deal seekers", "Essential purchases", "Price sensitive"]
            },
            2: {
                "name": "High Value Customers",
                "icon": "🟡",
                "description": "Affluent customers with high income and strong purchasing power. Regular spenders across premium categories.",
                "strategy": "Promote premium products, exclusive offers, VIP programs, and personalized recommendations.",
                "characteristics": ["High income", "Premium products", "Frequent buyers", "Brand loyal"]
            },
            3: {
                "name": "Premium Elite",
                "icon": "🔴",
                "description": "Top-tier customers with highest income and spending levels. Elite segment with luxury preferences.",
                "strategy": "VIP concierge service, luxury product lines, exclusive events, and white-glove treatment.",
                "characteristics": ["Highest income", "Luxury buyers", "Brand advocates", "Maximum lifetime value"]
            }
        }

        # Get cluster info
        info = cluster_details.get(cluster_num, {
            "name": f"Cluster {cluster_num}",
            "icon": "⚪",
            "description": "Customer segment identified",
            "strategy": "Standard marketing approach",
            "characteristics": ["Standard profile"]
        })

        return cluster_num, info

    except Exception as e:
        return None, {
            "name": "Prediction Error",
            "icon": "❌",
            "description": f"Failed to make prediction: {str(e)}",
            "strategy": "Please check your input values and try again.",
            "characteristics": []
        }

def main():

    # Sidebar for inputs
    st.sidebar.header("📋 Enter Customer Information")
    st.sidebar.markdown("---")

    # Demographics Section
    st.sidebar.subheader("👤 Demographics")

    Income = st.sidebar.number_input(
        "Annual Income ($)",
        min_value=0,
        max_value=200000,
        value=50000,
        step=1000,
        help="Customer's annual household income in dollars"
    )

    Age = st.sidebar.slider(
        "Age",
        min_value=18,
        max_value=85,
        value=45,
        help="Customer's age in years"
    )

    Education = st.sidebar.selectbox(
        "Education Level",
        options=["Basic", "2n Cycle", "Graduation", "Master", "PhD"],
        index=2,
        help="Highest level of education completed"
    )
    education_mapping = {'Basic': 1, '2n Cycle': 2, 'Graduation': 3, 'Master': 4, 'PhD': 5}
    Education_Encoded = education_mapping[Education]

    Marital_Status = st.sidebar.selectbox(
        "Marital Status",
        options=["Single", "Partner"],
        index=0,
        help="Current relationship status"
    )
    marital_status = 1 if Marital_Status == "Partner" else 0

    st.sidebar.markdown("---")

    # Family Section
    st.sidebar.subheader("👨‍👩‍👧‍👦 Family Structure")

    Kidhome = st.sidebar.number_input(
        "Children at Home",
        min_value=0,
        max_value=5,
        value=0,
        help="Number of children living at home"
    )

    Teenhome = st.sidebar.number_input(
        "Teenagers at Home",
        min_value=0,
        max_value=5,
        value=0,
        help="Number of teenagers living at home"
    )

    ChildrenCount = Kidhome + Teenhome
    Family_Size = ChildrenCount + (2 if marital_status == 1 else 1)

    st.sidebar.markdown("---")

    # Customer History Section
    st.sidebar.subheader("📅 Purchase History")

    Days_As_Customer = st.sidebar.number_input(
        "Days as Customer",
        min_value=0,
        max_value=5000,
        value=365,
        help="Number of days since customer registration"
    )

    Recency = st.sidebar.slider(
        "Days Since Last Purchase",
        min_value=0,
        max_value=100,
        value=30,
        help="Number of days since the last purchase"
    )

    st.sidebar.markdown("---")

    # Spending Section
    st.sidebar.subheader("💰 Annual Spending ($)")

    col1, col2 = st.sidebar.columns(2)

    with col1:
        MntWines = st.number_input("Wine", 0.0, 2000.0, 300.0, 10.0)
        MntMeatProducts = st.number_input("Meat", 0.0, 2000.0, 150.0, 10.0)
        MntSweetProducts = st.number_input("Sweets", 0.0, 500.0, 30.0, 5.0)

    with col2:
        MntFruits = st.number_input("Fruits", 0.0, 200.0, 20.0, 5.0)
        MntFishProducts = st.number_input("Fish", 0.0, 500.0, 50.0, 5.0)
        MntGoldProds = st.number_input("Gold", 0.0, 500.0, 40.0, 5.0)

    st.sidebar.markdown("---")

    # Purchase Channels Section
    st.sidebar.subheader("🛒 Purchase Channels")

    NumWebPurchases = st.sidebar.number_input(
        "Web Purchases",
        min_value=0,
        max_value=30,
        value=4,
        help="Number of purchases through website"
    )

    NumCatalogPurchases = st.sidebar.number_input(
        "Catalog Purchases",
        min_value=0,
        max_value=30,
        value=3,
        help="Number of purchases through catalog"
    )

    NumStorePurchases = st.sidebar.number_input(
        "Store Purchases",
        min_value=0,
        max_value=30,
        value=5,
        help="Number of in-store purchases"
    )

    NumDealsPurchases = st.sidebar.number_input(
        "Deals Purchases",
        min_value=0,
        max_value=20,
        value=2,
        help="Number of purchases with discount"
    )

    NumWebVisitsMonth = st.sidebar.number_input(
        "Website Visits per Month",
        min_value=0,
        max_value=20,
        value=5,
        help="Average monthly website visits"
    )

    st.sidebar.markdown("---")

    # Campaign Section
    st.sidebar.subheader("📢 Campaign Response")

    Total_Campaign_Accepted = st.sidebar.slider(
        "Campaigns Accepted",
        min_value=0,
        max_value=5,
        value=0,
        help="Total number of campaigns accepted"
    )

    Response = st.sidebar.selectbox(
        "Last Campaign Response",
        options=["No", "Yes"],
        index=0,
        help="Response to most recent campaign"
    )
    Response_val = 1 if Response == "Yes" else 0

    # Calculate derived features (with log transformation as in training)
    Total_Spent = np.log1p(
        MntWines + MntFruits + MntMeatProducts +
        MntFishProducts + MntSweetProducts + MntGoldProds
    )

    Total_Purchases = np.log1p(
        NumWebPurchases + NumCatalogPurchases + NumStorePurchases
    )

    # Prepare input data dictionary (23 features in exact order)
    input_data = {
        'Income': Income,
        'Recency': Recency,
        'MntWines': np.log1p(MntWines),
        'MntFruits': np.log1p(MntFruits),
        'MntMeatProducts': np.log1p(MntMeatProducts),
        'MntFishProducts': np.log1p(MntFishProducts),
        'MntSweetProducts': np.log1p(MntSweetProducts),
        'MntGoldProds': np.log1p(MntGoldProds),
        'NumDealsPurchases': np.log1p(NumDealsPurchases),
        'NumWebPurchases': np.log1p(NumWebPurchases),
        'NumCatalogPurchases': np.log1p(NumCatalogPurchases),
        'NumStorePurchases': np.log1p(NumStorePurchases),
        'NumWebVisitsMonth': NumWebVisitsMonth,
        'Response': np.log1p(Response_val),
        'Age': Age,
        'Days_As_Customer': Days_As_Customer,
        'ChildrenCount': ChildrenCount,
        'Family_Size': Family_Size,
        'marital_status': np.log1p(marital_status),
        'Total_Spent': Total_Spent,
        'Total_Purchases': Total_Purchases,
        'Total_Campaign_Accepted': np.log1p(Total_Campaign_Accepted),
        'Education_Encoded': Education_Encoded
    }

    # Main content area
    st.subheader("📊 Customer Profile Summary")

    # Display key metrics
    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("💵 Annual Income", f"${Income:,}")
        st.metric("👤 Age", f"{Age} years")

    with col2:
        st.metric("👨‍👩‍👧‍👦 Family Size", Family_Size)
        st.metric("📅 Customer Tenure", f"{Days_As_Customer} days")

    with col3:
        total_raw_spending = MntWines + MntFruits + MntMeatProducts + MntFishProducts + MntSweetProducts + MntGoldProds
        st.metric("💰 Total Annual Spending", f"${total_raw_spending:.0f}")
        st.metric("📚 Education", Education)

    with col4:
        total_purchases = NumWebPurchases + NumCatalogPurchases + NumStorePurchases
        st.metric("🛍️ Total Purchases", total_purchases)
        st.metric("📢 Campaigns Accepted", Total_Campaign_Accepted)

    st.markdown("---")

    # Prediction button
    if st.button("🎯 Segment Customer", type="primary", use_container_width=True):

        with st.spinner("🔄 Analyzing customer profile..."):
            cluster_num, cluster_info = segment_customers(input_data)

            if cluster_num is not None:
                # Success - display results
                st.balloons()
                st.success("✅ Segmentation Complete!")

                # Display cluster result card
                st.markdown(f"""
                <div style="
                    padding: 2.5rem;
                    border-radius: 15px;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    color: white;
                    text-align: center;
                    margin: 1.5rem 0;
                    box-shadow: 0 10px 25px rgba(0,0,0,0.2);
                ">
                    <h1 style="margin: 0; font-size: 4rem;">{cluster_info['icon']}</h1>
                    <h2 style="margin: 1rem 0 0.5rem 0;">Cluster {cluster_num}: {cluster_info['name']}</h2>
                    <p style="margin: 0; font-size: 1.2rem; opacity: 0.95;">{cluster_info['description']}</p>
                </div>
                """, unsafe_allow_html=True)

                # Two-column layout for details
                detail_col1, detail_col2 = st.columns(2)

                with detail_col1:
                    st.subheader("📈 Marketing Strategy")
                    st.info(f"**Recommended Approach:**\n\n{cluster_info['strategy']}")

                    if 'characteristics' in cluster_info:
                        st.subheader("🔍 Key Characteristics")
                        for char in cluster_info['characteristics']:
                            st.write(f"• {char}")

                with detail_col2:
                    st.subheader("💡 Profile Insights")

                    # Spending pattern
                    st.markdown("**Spending Pattern:**")
                    if total_raw_spending > 1000:
                        st.success("✅ High spender - Premium product target")
                    elif total_raw_spending > 500:
                        st.info("📊 Moderate spender - Mid-range products")
                    else:
                        st.warning("💰 Budget conscious - Value offerings")

                    # Engagement level
                    st.markdown("**Engagement Level:**")
                    if Total_Campaign_Accepted >= 3:
                        st.success("🌟 Highly engaged - Very responsive")
                    elif Total_Campaign_Accepted >= 1:
                        st.info("📧 Moderately engaged - Selective")
                    else:
                        st.warning("💤 Low engagement - Needs activation")

                    # Purchase preference
                    st.markdown("**Purchase Preference:**")
                    if NumWebPurchases > NumStorePurchases:
                        st.write("🌐 Digital-first customer")
                    elif NumStorePurchases > NumWebPurchases:
                        st.write("🏪 In-store shopper")
                    else:
                        st.write("🔄 Omnichannel customer")

            else:
                # Error case
                st.error("❌ Prediction Error")
                st.warning(f"**Details:** {cluster_info['description']}")

                with st.expander("🔧 Troubleshooting"):
                    st.markdown("""
                    **Common Issues:**

                    1. **Model File Missing**
                       - Ensure `classifier.pkl` is uploaded to GitHub repository
                       - File should be in the root directory

                    2. **Dependencies Not Installed**
                       - Check `requirements.txt` has all packages
                       - Verify package versions match training environment

                    3. **Feature Mismatch**
                       - Model expects exactly 23 features
                       - Features must be in specific order

                    **Need Help?**
                    - Check Streamlit Cloud logs (Manage App → Logs)
                    - Verify model file size (should be > 1 MB)
                    - Ensure all inputs are valid numbers
                    """)

    # Add sample data button
    st.markdown("---")

    col_sample1, col_sample2, col_sample3 = st.columns([1, 1, 1])

    with col_sample2:
        if st.button("📝 Try Sample Data", use_container_width=True):
            st.info("💡 Adjust the values in the sidebar and click 'Segment Customer' to see the prediction!")

# Footer
st.markdown("---")
st.markdown("""
<div style="text-align: center; color: #888; padding: 1rem; font-size: 0.9rem;">
    <p><strong>Customer Segmentation ML Application</strong></p>
    <p>Built with ❤️ using Streamlit • K-Means Clustering + Ensemble Learning</p>
    <p>Model Accuracy: 98.2% • 4 Customer Segments • Real-time Predictions</p>
</div>
""", unsafe_allow_html=True)

if __name__ == '__main__':
    main()